spring.application.name=mecanica-dm-api

spring.datasource.url=jdbc:postgresql://${DB_HOST:db}:5432/${POSTGRES_DB:mecanicadmdb}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=validate
spring.messages.encoding=UTF-8
spring.messages.basename=i18n/messages
spring.flyway.enabled=true
spring.flyway.clean-disabled=true

api.security.token.secret=development

cors.allowed-origins=*

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

server.error.include-stacktrace=never

springdoc.swagger-ui.docExpansion=none
