apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: mecanicadm
type: Opaque
stringData:
  postgres-user: postgres
  postgres-password: password123
  db-url: jdbc:postgresql://postgres-db:5432/mecanicadm