apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../manifests/namespace.yaml
  - ../manifests/app-configmap.yaml
  - ../manifests/db-secret.yaml
  - ../manifests/postgres/postgres-configmap.yaml
  - ../manifests/postgres/postgres-deployment.yaml
  - ../manifests/postgres/postgres-service.yaml
  - ../manifests/app-deployment.yaml
  - ../manifests/app-service.yaml
  - ../manifests/app-hpa.yaml