apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - app-configmap.yaml
  - db-secret.yaml
  - ./postgres/postgres-configmap.yaml
  - ./postgres/postgres-deployment.yaml
  - ./postgres/postgres-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-hpa.yaml